//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminEcomerceVersion_2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ecom_staff
    {
        public int staff_id { get; set; }
        public Nullable<int> brand_id { get; set; }
        public Nullable<int> store_id { get; set; }
        public string role_type { get; set; }
        public string email { get; set; }
        public string is_email_verified { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public string mobile_num { get; set; }
        public string wa_num { get; set; }
        public string address_en { get; set; }
        public string address_ar { get; set; }
        public string loc_lat { get; set; }
        public string loc_lng { get; set; }
        public Nullable<int> created_by { get; set; }
        public Nullable<System.DateTime> created_on { get; set; }
        public Nullable<int> updated_by { get; set; }
        public Nullable<System.DateTime> updated_on { get; set; }
        public string is_active { get; set; }
        public string is_firebase_account_created { get; set; }
        public string firebase_initial_pw { get; set; }
    }
}
